### ISSUE TITLE
如何转发所有流量

### ISSUE THREAD

**Issue by Windforce17** [black-binary/ap-kcp#1]
RT, 不仅仅是转发带1.1.1.1:5000

**Comment by yue-qiu** [comment]
把原数据包里的目的ip和端口抽出来？

**Comment by black-binary** [comment]
这种需求的话，服务端开一个socks5/http代理服务器监听127.0.0.1:5000， 1.1.1.1:5000换成127.0.0.1:5000

**Comment by Windforce17** [comment]
加个选项吧，懒得起代理了23333

**Comment by black-binary** [comment]
这个项目提供的是一个库或者一个隧道，而不是代理，如果有这种需求建议配合其他软件使用，或者起一个新项目调用这个库
